# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


# Api.pull_searched_breweries('alabama')
# Api.pull_searched_breweries('arkansas')
# Api.pull_searched_breweries('arizona')
# Api.pull_searched_breweries('alaska')
# Api.pull_searched_breweries('california')
# Api.pull_searched_breweries('colorado')
# Api.pull_searched_breweries('connecticut')
# Api.pull_searched_breweries('delaware')
# Api.pull_searched_breweries('florida')
# Api.pull_searched_breweries('georgia')
# Api.pull_searched_breweries('hawaii')
# Api.pull_searched_breweries('idaho')
# Api.pull_searched_breweries('illinois')
# Api.pull_searched_breweries('indiana')
# Api.pull_searched_breweries('iowa')
# Api.pull_searched_breweries('kansas')
# Api.pull_searched_breweries('kentucky')
# Api.pull_searched_breweries('louisana')
# Api.pull_searched_breweries('maine')
# Api.pull_searched_breweries('maryland')
# Api.pull_searched_breweries('michigan')
# Api.pull_searched_breweries('massachusetts')
# Api.pull_searched_breweries('minnesota')
# Api.pull_searched_breweries('mississippi')
# Api.pull_searched_breweries('missouri')
# Api.pull_searched_breweries('montana')
# Api.pull_searched_breweries('nebraska')
# Api.pull_searched_breweries('nevada')
# Api.pull_searched_breweries('new_hampshire')
# Api.pull_searched_breweries('new_jersey')
# Api.pull_searched_breweries('new_mexico')
# Api.pull_searched_breweries('north_carolina')
# Api.pull_searched_breweries('north_dakota')
# Api.pull_searched_breweries('ohio')
# Api.pull_searched_breweries('oklahoma')
# Api.pull_searched_breweries('oregon')
# Api.pull_searched_breweries('pennsylvania')
# Api.pull_searched_breweries('rhode_island')
# Api.pull_searched_breweries('south_carolina')
# Api.pull_searched_breweries('south_dakota')
# Api.pull_searched_breweries('tennessee')
# Api.pull_searched_breweries('texas') 
# # Texas will break seed file due to lack of addresses
# Api.pull_searched_breweries('utah')
# Api.pull_searched_breweries('vermont')
# Api.pull_searched_breweries('virginia')
# Api.pull_searched_breweries('washington')
# Api.pull_searched_breweries('west_virginia')
# Api.pull_searched_breweries('wyoming')


Favorite.create(user_id: 17, brewery_id: 76)
Favorite.create(user_id: 17, brewery_id: 86)
Favorite.create(user_id: 17, brewery_id: 107)
Favorite.create(user_id: 17, brewery_id: 132)
Favorite.create(user_id: 17, brewery_id: 67)
Favorite.create(user_id: 18, brewery_id: 76)
Favorite.create(user_id: 18, brewery_id: 79)
Favorite.create(user_id: 18, brewery_id: 200)
Favorite.create(user_id: 18, brewery_id: 202)
Favorite.create(user_id: 18, brewery_id: 29)
Favorite.create(user_id: 18, brewery_id: 387)
Favorite.create(user_id: 18, brewery_id: 99)
Favorite.create(user_id: 18, brewery_id: 4281)

